---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    fabric8.io/git-commit: 9f23a04a1c3cfcb0a3a3638792137305b5ddd004
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/rh-maggarwa/amq-streams.git
  labels:
    expose: "true"
    app: kafka-producer-ocp
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: org.redhat
  name: kafka-producer-ocp
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: kafka-producer-ocp
