---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: f7fb61983edd24fcfd323f936246ab544f693564
      fabric8.io/git-branch: main
      fabric8.io/git-url: https://github.com/sainijit/kafka-producer.git
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: kafka-producer-ocp
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: org.redhat
    name: kafka-producer-ocp
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: kafka-producer-ocp
      provider: fabric8
      group: org.redhat
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: f7fb61983edd24fcfd323f936246ab544f693564
      fabric8.io/git-branch: main
      fabric8.io/git-url: https://github.com/sainijit/kafka-producer.git
    labels:
      app: kafka-producer-ocp
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: org.redhat
    name: kafka-producer-ocp
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: kafka-producer-ocp
      provider: fabric8
      group: org.redhat
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: f7fb61983edd24fcfd323f936246ab544f693564
          fabric8.io/git-branch: main
          fabric8.io/git-url: https://github.com/sainijit/kafka-producer.git
        labels:
          app: kafka-producer-ocp
          provider: fabric8
          version: 0.0.1-SNAPSHOT
          group: org.redhat
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: redhat/kafka-producer-ocp:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      fabric8.io/git-commit: f7fb61983edd24fcfd323f936246ab544f693564
      fabric8.io/git-branch: main
      fabric8.io/git-url: https://github.com/sainijit/kafka-producer.git
    labels:
      expose: "true"
      app: kafka-producer-ocp
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: org.redhat
    name: kafka-producer-ocp
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: kafka-producer-ocp
